### ISSUE TITLE
Thanks for mentioning my tutorial

### ISSUE THREAD

**Issue by cj-praveen** [alehee/cheeseBot#1]
> random meme scraping by [this](https://sijey-praveen.medium.com/how-to-make-a-discord-meme-bot-using-15-lines-of-python-code-a2c7f6284d9f) tutorial

Hello @alehee !
Thanks for mentioning my tutorial in [README.md](https://github.com/alehee/cheeseBot/blob/main/README.md) file.

**Comment by alehee** [comment]
It is great, simple and easy to implement, couldn't walk pass by it!
